---

sudo: required
dist: trusty
language: cpp
services:
  - docker

git:
  submodules: false

matrix:
  fast_finish: true
  allow_failures:
    - os: linux
      env: MAKE_COMMAND="docs upload-docs"
  include:
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: MAKE_COMMAND="osx"
    - os: linux
      compiler: gcc
      env:
        - MAKE_COMMAND="linux tar deb rpm"
        - UPLOAD_TO_GH=yes
    - os: linux
      env:
        - MAKE_COMMAND="windows zip"
        - UPLOAD_TO_GH=yes
    - os: linux
      env: MAKE_COMMAND="docs upload-docs"

before_install:
  - git submodule update --init --recursive
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo pip install awscli
    fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e075a4f5a37b0c115fa8
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always

script:
  - make $MAKE_COMMAND -C package

before_deploy:
  - "mkdir -p upload"
  - "mv package/*.tar.bz2 package/*.deb package/*.rpm package/*.zip upload || true"
  - "rm -f upload/*source*"

deploy:
  provider: releases
  api_key:
    secure: fJMRmWSoBrm2hy6FDwhp7flHJhcXPZWE7gPluYT/G4K4uGf/QaFS0yKiTEXYEPWzBPUdidZxOKX427/rlmXyrl7ZfrUfn5k/cctc1aYpV5khtVWFCxlTbltzPefq8B7DkSDlQSnh9qB8e6J4E7xQd8zak6spjRntFBXafdvHM5E=
  file: "upload/*"
  file_glob: true
  on:
    repo: konstructs/client
    tags: true
    condition: "$UPLOAD_TO_GH = yes"
